Repository securesign/secure-sign-operator, pull requests merged in 2024-05, with the labels that each got.

#354 update rekor-search-ui image
  controllers/constants/images.go
Labels: approved

#356 update fbc's
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#357 catalog: remove alpha channel, add rhtas-1-0
  Makefile
  controllers/rekor/actions/initialize.go
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved, lgtm

#360 chore(rekor-search-ui) update image
  controllers/constants/images.go
Labels: approved, lgtm

#361 chore(bundle): make bundle with new image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved

#362 fbc-images
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#366 Upgrade operator maturity level
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#367 update-naming-in-fbc
  Makefile
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved, lgtm

#368 update-label-in-bundle
  bundle.Dockerfile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  fbc/generate-fbc.sh
Labels: approved

#370 update bundle image
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#371 adding dep params for depricated image check
  .tekton/fbc-v4-13-pull-request.yaml
  .tekton/fbc-v4-13-push.yaml
  .tekton/fbc-v4-14-pull-request.yaml
  .tekton/fbc-v4-14-push.yaml
  .tekton/fbc-v4-15-pull-request.yaml
  .tekton/fbc-v4-15-push.yaml
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved

#372 Remove analytics field from Securesign sample
  README.md
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/samples/rhtas_v1alpha1_securesign.yaml
Labels: approved, lgtm

#373 update-images
  controllers/constants/images.go
Labels: approved, lgtm

#374 run make bundle
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved

#375 fbc-images
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#358 Securesign 861
  .github/workflows/upgrade.yml
  Makefile
  e2e/byodb_test.go
  e2e/cli_server_test.go
  e2e/common_install_test.go
  e2e/config_update_test.go
  e2e/key_autodiscovery_test.go
  e2e/provided_certs_test.go
  e2e/support/common.go
  e2e/support/upgrade.go
  e2e/tas_e2e_suite_test.go
  e2e/upgrade_test.go
  fbc/generate-fbc.sh
  go.mod
  go.sum
Labels: approved, lgtm

#378 Disable kind registry to free node memory
  .github/workflows/main.yml
  .github/workflows/upgrade.yml
  ci/config.yaml
  e2e/upgrade_test.go
Labels: approved, lgtm

#377 [SECURESIGN-957] Change Deployment strategy to Recreate for services with PVCs
  controllers/rekor/utils/rekor_deployment.go
  controllers/trillian/utils/trillian-db.go
Labels: approved, lgtm

#379 run-make-bundle
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved

#380 update fbc images
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#381 [SECURESIGN-938] Add TUF keys to securesign sample
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/samples/rhtas_v1alpha1_securesign.yaml
Labels: approved, lgtm

#382 update fbcs
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#384 add annotation
  bundle.Dockerfile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved

#385 trigger-bundle-build
  bundle.Dockerfile
Labels: approved

#386 fbc-images
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#387 Remove dependency on sigstore-ocp
  .github/workflows/main.yml
  .github/workflows/upgrade.yml
  ci/keycloak/operator/base/kustomization.yaml
  ci/keycloak/operator/base/namespace.yaml
  ci/keycloak/operator/base/subscription.yaml
  ci/keycloak/operator/overlay/kind/kustomization.yaml
  ci/keycloak/operator/overlay/kind/patch.yaml
  ci/keycloak/resources/base/keycloak.yaml
  ci/keycloak/resources/base/kustomization.yaml
  ci/keycloak/resources/base/realm.yaml
  ci/keycloak/resources/base/tas-client.yaml
  ci/keycloak/resources/base/user.yaml
  ci/keycloak/resources/example-user.yaml
  ci/keycloak/resources/overlay/kind/keycloak-svc.yaml
  ci/keycloak/resources/overlay/kind/keycloak_patch.yaml
  ci/keycloak/resources/overlay/kind/kustomization.yaml
  ci/keycloak/resources/overlay/kind/realm_patch.yaml
  ci/openshift/tas-keycloak-install.sh
  hack/up.sh
Labels: approved, lgtm

#365 fix: Set the common name of the Fulcio cert automatically
  api/v1alpha1/fulcio_types.go
  api/v1alpha1/fulcio_types_test.go
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  controllers/common/utils/kubernetes/common.go
  controllers/common/utils/kubernetes/ingress.go
  controllers/fulcio/actions/generate_cert.go
  controllers/fulcio/utils/fulcio_secrets.go
Labels: approved, lgtm

#383 Increase test timeout
  e2e/cli_server_test.go
Labels: approved, lgtm

#392 Bump operator's version for 1.1.0 release
  .github/workflows/upgrade.yml
  Dockerfile.rhtas-operator.rh
  Makefile
  bundle.Dockerfile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#396 update-konflux-paths-for-1.0
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved

#402 [release-1.0] Bump operator version to 1.0.2
  .github/workflows/upgrade.yml
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#388 rm kube-rbac-proxy
  bundle/manifests/rhtas-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/rhtas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/rbac/kustomization.yaml
Labels: approved

#369 Handle error when ctlog unable to generate public key
  controllers/ctlog/actions/handle_keys.go
Labels: approved, lgtm

#346 Add annotation to pause resource reconciliation
  controllers/annotations/annotations.go
  controllers/common/action/base_action.go
  controllers/ctlog/ctlog_controller.go
  controllers/fulcio/fulcio_controller.go
  controllers/rekor/rekor_controller.go
  controllers/securesign/securesign_controller.go
  controllers/trillian/trillian_controller.go
  controllers/tuf/tuf_controller.go
  go.mod
  go.sum
Labels: enhancement, approved, lgtm

#407 [release-1.0] Extract fbc sources code to separate repository
  .github/workflows/upgrade.yml
  .tekton/fbc-v4-13-pull-request.yaml
  .tekton/fbc-v4-13-push.yaml
  .tekton/fbc-v4-14-pull-request.yaml
  .tekton/fbc-v4-14-push.yaml
  .tekton/fbc-v4-15-pull-request.yaml
  .tekton/fbc-v4-15-push.yaml
  fbc/fbc-preflight-testing-steps
  fbc/generate-fbc.sh
  fbc/v4.13/catalog.Dockerfile
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/devfile.yaml
  fbc/v4.13/graph.yaml
  fbc/v4.13/licenses/license.txt
  fbc/v4.13/v4.13/.empty
  fbc/v4.14/catalog.Dockerfile
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/devfile.yaml
  fbc/v4.14/graph.yaml
  fbc/v4.14/licenses/license.txt
  fbc/v4.14/v4.14/.empty
  fbc/v4.15/catalog.Dockerfile
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/ci
  fbc/v4.15/devfile.yaml
  fbc/v4.15/graph.yaml
  fbc/v4.15/licenses/license.txt
  fbc/v4.15/v4.15/.empty
Labels: approved, lgtm

#391 Use SecurityContextConstraints resource to identify OCP environment
  controllers/common/utils/kubernetes/common.go
Labels: approved, lgtm
