Repository securesign/secure-sign-operator, pull requests merged in 2024-07, with the labels that each got.

#464 Fix trillian-db scc
  .github/workflows/main.yml
  internal/controller/common/utils/kubernetes/common.go
  internal/controller/trillian/actions/db/deployment.go
  internal/controller/trillian/utils/trillian-db.go
Labels: approved, lgtm

#486 [SECURESIGN-1049] adding securesign quay url
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved, lgtm

#487 [SECURESIGN-1049] Changing push url to securesign
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved, lgtm

#465 [SECURESIGN-663] Add option to set an external ctlog service
  api/v1alpha1/common.go
  api/v1alpha1/fulcio_types.go
  api/v1alpha1/fulcio_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  internal/controller/fulcio/actions/deployment.go
  internal/controller/fulcio/utils/errors.go
  internal/controller/fulcio/utils/fulcio_deployment.go
  internal/controller/fulcio/utils/fulcio_deployment_test.go
Labels: approved, lgtm

#485 Disable eks testing on push events
  .github/workflows/main.yml
Labels: approved, lgtm

#491 Inject CA trust bundle into managed containers and set SSL_CERT_DIR
  api/v1alpha1/rekor_types_test.go
  api/v1alpha1/trillian_types_test.go
  docs/custom-ca.md
  internal/controller/annotations/annotations.go
  internal/controller/annotations/annotations_test.go
  internal/controller/common/utils/set_trusted_ca.go
  internal/controller/common/utils/set_trusted_ca_test.go
  internal/controller/ctlog/actions/deployment.go
  internal/controller/fulcio/utils/fulcio_deployment.go
  internal/controller/fulcio/utils/fulcio_deployment_test.go
  internal/controller/rekor/actions/server/deployment.go
  internal/controller/securesign/actions/ensure_ctlog.go
  internal/controller/securesign/actions/ensure_fulcio.go
  internal/controller/securesign/actions/ensure_rekor.go
  internal/controller/securesign/actions/ensure_trillian.go
  internal/controller/securesign/actions/ensure_tuf.go
  internal/controller/securesign/actions/segment_backup_cronjob.go
  internal/controller/securesign/actions/segment_backup_job.go
  internal/controller/trillian/actions/logserver/deployment.go
  internal/controller/trillian/actions/logsigner/deployment.go
Labels: approved, lgtm

#497 Bumb source version of operator for upgrade scenario
  .github/workflows/main.yml
Labels: approved, lgtm

#495 Use Gomega parameter passed by eventually to create assertions
  internal/controller/ctlog/ctlog_controller_test.go
  internal/controller/ctlog/ctlog_hot_update_test.go
  internal/controller/fulcio/fulcio_controller_test.go
  internal/controller/fulcio/fulcio_hot_update_test.go
  internal/controller/rekor/rekor_controller_test.go
  internal/controller/rekor/rekor_hot_update_test.go
  internal/controller/trillian/trillian_controller_test.go
  internal/controller/tuf/tuf_controller_test.go
  internal/controller/tuf/tuf_hot_update_test.go
  test/e2e/common_install_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#499 Store K8s dump into file
  .github/workflows/main.yml
  .gitignore
  test/e2e/support/archive.go
  test/e2e/support/common.go
Labels: approved, lgtm

#501 [SECURESIGN-1206] Making segment backup job proxy aware
  internal/controller/securesign/actions/segment_backup_cronjob.go
  internal/controller/securesign/actions/segment_backup_job.go
Labels: approved, lgtm

#503 update-clamav-task
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved, lgtm

#488 feat: provide host name option for CLI and search ui
  api/v1alpha1/rekor_types.go
  cmd/main.go
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  internal/clidownload/component.go
  internal/controller/rekor/actions/ui/ingress.go
Labels: approved, lgtm

#505 Namespace deletion check in Reconcile function
  internal/controller/ctlog/ctlog_controller.go
  internal/controller/ctlog/ctlog_hot_update_test.go
  internal/controller/fulcio/fulcio_controller.go
  internal/controller/rekor/rekor_controller.go
  internal/controller/rekor/rekor_hot_update_test.go
  internal/controller/securesign/securesign_controller.go
  internal/controller/trillian/trillian_controller.go
  internal/controller/tuf/tuf_controller.go
  test/e2e/support/archive.go
  test/e2e/support/common.go
Labels: approved, lgtm

#506 Create tree event contains Merkle tree id
  internal/controller/ctlog/actions/createTree.go
Labels: approved, lgtm

#502 SECURESIGN-1207: fix SBJ breaking on update
  internal/controller/common/utils/kubernetes/job.go
  internal/controller/securesign/actions/segment_backup_job.go
Labels: approved, lgtm, jira/valid-reference

#351 Update Rekor controller behavior to preserve generated keys
  api/v1alpha1/rekor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  internal/controller/annotations/annotations.go
  internal/controller/common/utils/kubernetes/common.go
  internal/controller/common/utils/kubernetes/secret.go
  internal/controller/ctlog/actions/handle_fulcio_root.go
  internal/controller/ctlog/actions/handle_fulcio_root_test.go
  internal/controller/fulcio/fulcio_controller_test.go
  internal/controller/rekor/actions/server/createTree.go
  internal/controller/rekor/actions/server/deployment.go
  internal/controller/rekor/actions/server/generate_signer.go
  internal/controller/rekor/actions/server/resolve_pub_key.go
  internal/controller/rekor/actions/server/resolve_pub_key_test.go
  internal/controller/rekor/rekor_controller_test.go
  internal/controller/rekor/rekor_hot_update_test.go
  internal/controller/rekor/suite_test.go
  internal/testing/action/result.go
  internal/testing/action/support.go
  internal/testing/http/mock.go
  test/e2e/support/common.go
Labels: approved, lgtm

#509 SECURESIGN-1226: Update Rekor's treeID when it change
  internal/controller/rekor/actions/server/resolve_tree.go
  internal/controller/rekor/actions/server/resolve_tree_test.go
  internal/controller/rekor/rekor_controller.go
  internal/controller/rekor/suite_test.go
Labels: approved, lgtm, jira/valid-reference

#511 Remove finalizer before interupting reconcile function
  internal/controller/securesign/securesign_controller.go
Labels: approved, lgtm

#510 SECURESIGN-1227: Update CTlog's treeID when it change
  internal/controller/ctlog/actions/createTree.go
  internal/controller/ctlog/actions/resolve_tree.go
  internal/controller/ctlog/actions/resolve_tree_test.go
  internal/controller/ctlog/ctlog_controller.go
Labels: approved, lgtm, jira/valid-reference

#513 doc: Rotation the signer key for Rekor service
  docs/rekor-key-rotation.md
Labels: approved, lgtm

#519 Fix incorrect number of parameters for SBJ error logging
  internal/controller/securesign/actions/segment_backup_job.go
Labels: approved, lgtm

#518 SECURESIGN-1250 | Targets are not coming up with monitoring enabled.
  bundle/manifests/rhtas.redhat.com_rekors.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  internal/clidownload/component.go
  internal/controller/common/utils/kubernetes/service.go
  internal/controller/ctlog/actions/constants.go
  internal/controller/ctlog/actions/deployment.go
  internal/controller/ctlog/actions/monitoring.go
  internal/controller/ctlog/actions/service.go
  internal/controller/ctlog/ctlog_controller_test.go
  internal/controller/ctlog/ctlog_hot_update_test.go
  internal/controller/ctlog/utils/ctlog_deployment.go
  internal/controller/fulcio/actions/constants.go
  internal/controller/fulcio/actions/ingress.go
  internal/controller/fulcio/actions/monitoring.go
  internal/controller/fulcio/actions/service.go
  internal/controller/fulcio/fulcio_controller_test.go
  internal/controller/fulcio/utils/fulcio_deployment.go
  internal/controller/rekor/actions/constants.go
  internal/controller/rekor/actions/redis/svc.go
  internal/controller/rekor/actions/server/ingress.go
  internal/controller/rekor/actions/server/monitoring.go
  internal/controller/rekor/actions/server/svc.go
  internal/controller/rekor/actions/ui/svc.go
  internal/controller/rekor/utils/rekor_deployment.go
  internal/controller/trillian/actions/constants.go
  internal/controller/trillian/actions/db/svc.go
  internal/controller/trillian/actions/logserver/deployment.go
  internal/controller/trillian/actions/logserver/monitoring.go
  internal/controller/trillian/actions/logserver/service.go
  internal/controller/trillian/actions/logsigner/deployment.go
  internal/controller/trillian/actions/logsigner/monitoring.go
  internal/controller/trillian/actions/logsigner/service.go
  internal/controller/trillian/utils/trillian-deployment.go
  internal/controller/tuf/actions/servise.go
Labels: approved, lgtm

#520 chore: add preflight checks to pipelines
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved, lgtm

#522 e2e: Use deployment to verify configuration update of component
  test/e2e/config_update_test.go
Labels: approved, lgtm

#529 rekor: Initialize action execute when targeted condition status is false
  internal/controller/rekor/actions/initialize.go
  internal/controller/rekor/actions/redis/initialize.go
  internal/controller/rekor/actions/server/initialize.go
  internal/controller/rekor/actions/server/resolve_pub_key.go
  internal/controller/rekor/actions/server/resolve_pub_key_test.go
  internal/controller/rekor/actions/ui/initialize.go
  test/e2e/support/common.go
Labels: approved, lgtm

#512 SECURESIGN-568: Extend Rekor API to support sharding configuration
  api/v1alpha1/rekor_types.go
  api/v1alpha1/rekor_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_rekors.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  docs/rekor-key-rotation.md
  docs/rekor-sharding.md
  internal/controller/common/utils/kubernetes/config_map.go
  internal/controller/rekor/actions/server/servrConfig.go
  internal/controller/rekor/actions/server/sharding_config.go
  internal/controller/rekor/actions/server/sharding_config_test.go
  internal/controller/rekor/rekor_controller.go
  internal/testing/errors/helper.go
Labels: approved, lgtm, jira/valid-reference

#517 [SECURESIGN-574] | Independently deployable CTlog Changes
  api/v1alpha1/ctlog_types.go
  api/v1alpha1/ctlog_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_ctlogs.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_ctlogs.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  internal/controller/ctlog/actions/constants.go
  internal/controller/ctlog/actions/deployment.go
  internal/controller/ctlog/actions/resolve_tree.go
  internal/controller/ctlog/actions/resolve_tree_test.go
  internal/controller/ctlog/actions/serverConfig.go
  internal/controller/ctlog/utils/ctlog_deployment.go
  internal/controller/ctlog/utils/errors.go
Labels: approved, lgtm, ok-to-test

#532 SECURESIGN-1275: Enable RecoverPanic on controllers
  cmd/main.go
  internal/metrics/metrics.go
Labels: approved, lgtm, jira/valid-reference
