Repository securesign/secure-sign-operator, pull requests merged in 2024-03, with the labels that each got.

#235 run make bundle
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_ctlogs.yaml
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_rekors.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  bundle/manifests/rhtas.redhat.com_trillians.yaml
  bundle/manifests/rhtas.redhat.com_tufs.yaml
Labels: approved, lgtm

#236 Add API validation rules for CTlog and Fulcio resources
  api/v1alpha1/ctlog_types.go
  api/v1alpha1/ctlog_types_test.go
  api/v1alpha1/fulcio_types.go
  api/v1alpha1/fulcio_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rhtas.redhat.com_ctlogs.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  controllers/fulcio/actions/generate_cert.go
  controllers/fulcio/utils/fulcio_deployment.go
Labels: approved, lgtm

#237 Add FBC images for GA
  fbc/v4.12/catalog.Dockerfile
  fbc/v4.12/catalog/rhtas-operator/catalog.json
  fbc/v4.12/devfile.yaml
  fbc/v4.12/graph.yaml
  fbc/v4.12/v4.12/.empty
  fbc/v4.13/catalog.Dockerfile
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/devfile.yaml
  fbc/v4.13/graph.yaml
  fbc/v4.13/v4.13/.empty
  fbc/v4.14/catalog.Dockerfile
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/devfile.yaml
  fbc/v4.14/graph.yaml
  fbc/v4.14/v4.14/.empty
Labels: approved, lgtm

#245 Fix status conditions
  controllers/ctlog/actions/initialize.go
  controllers/rekor/actions/server/generate_signer.go
  controllers/rekor/actions/server/initialize.go
  controllers/rekor/rekor_controller_test.go
  controllers/securesign/actions/update_status.go
  controllers/trillian/actions/db/initialize.go
  controllers/trillian/actions/logserver/initialize.go
  controllers/trillian/actions/logsigner/initialize.go
Labels: approved, lgtm

#227 Split Client server into two images
  controllers/constants/images.go
  main.go
Labels: approved, lgtm

#246 Add license to FBC images
  .tekton/fbc-v4-13-pull-request.yaml
  fbc/v4.13/catalog.Dockerfile
  fbc/v4.13/licenses/license.txt
  fbc/v4.14/catalog.Dockerfile
  fbc/v4.14/licenses/license.txt
Labels: approved

#243 Adding 4.15 FBC images
  fbc/v4.15/catalog.Dockerfile
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/devfile.yaml
  fbc/v4.15/graph.yaml
  fbc/v4.15/licenses/license.txt
  fbc/v4.15/v4.15/.empty
Labels: approved, lgtm

#244 Add LocalObejctReference to v1alpha1 api
  api/v1alpha1/common.go
  api/v1alpha1/ctlog_types.go
  api/v1alpha1/ctlog_types_test.go
  api/v1alpha1/fulcio_types.go
  api/v1alpha1/fulcio_types_test.go
  api/v1alpha1/rekor_types.go
  api/v1alpha1/rekor_types_test.go
  api/v1alpha1/trillian_types.go
  api/v1alpha1/trillian_types_test.go
  api/v1alpha1/tuf_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rhtas.redhat.com_ctlogs.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_trillians.yaml
  config/crd/bases/rhtas.redhat.com_tufs.yaml
  controllers/ctlog/actions/handle_fulcio_root.go
  controllers/ctlog/actions/handle_keys.go
  controllers/ctlog/actions/serverConfig.go
  controllers/ctlog/ctlog_hot_update_test.go
  controllers/fulcio/actions/generate_cert.go
  controllers/fulcio/actions/servrConfig.go
  controllers/fulcio/fulcio_controller_test.go
  controllers/fulcio/fulcio_hot_update_test.go
  controllers/fulcio/utils/fulcio_deployment.go
  controllers/rekor/actions/server/generate_signer.go
  controllers/rekor/actions/server/servrConfig.go
  controllers/rekor/rekor_hot_update_test.go
  controllers/rekor/utils/rekor_deployment.go
  controllers/trillian/actions/db/handle_secret.go
  controllers/trillian/trillian_controller_test.go
  controllers/trillian/utils/trillian-db.go
  controllers/trillian/utils/trillian-deployment.go
  controllers/tuf/actions/generate_cert.go
  controllers/tuf/tuf_controller_test.go
  controllers/tuf/tuf_hot_update_test.go
  e2e/byodb_test.go
  e2e/config_update_test.go
  e2e/key_autodiscovery_test.go
  e2e/provided_certs_test.go
Labels: approved, lgtm

#248 Run make bundle
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_ctlogs.yaml
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  config/manager/kustomization.yaml
Labels: approved, lgtm

#251 Update FBC images to recent snapshot
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#252 Fix generated Fulcio root certificate requirements
  api/v1alpha1/fulcio_types.go
  api/v1alpha1/fulcio_types_test.go
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  controllers/ctlog/actions/handle_fulcio_root.go
  controllers/ctlog/actions/handle_keys.go
  controllers/fulcio/actions/generate_cert.go
  controllers/fulcio/utils/fulcio_secrets.go
  controllers/rekor/actions/server/generate_signer.go
  e2e/provided_certs_test.go
Labels: approved, lgtm

#255 chore: bump fulcio, trillian and ct
  go.mod
  go.sum
Labels: approved, lgtm

#253 chore: Update to latest images
  controllers/constants/images.go
Labels: approved, lgtm

#250 Update Konflux CEL expressions
  .tekton/fbc-v4-13-pull-request.yaml
  .tekton/fbc-v4-13-push.yaml
  .tekton/fbc-v4-14-pull-request.yaml
  .tekton/fbc-v4-14-push.yaml
  .tekton/fbc-v4-15-pull-request.yaml
  .tekton/fbc-v4-15-push.yaml
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved, lgtm

#258 deps(netcat): replace custom netcat with ose-tools
  controllers/constants/images.go
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.15/catalog/rhtas-operator/catalog.json
Labels: approved, lgtm

#256 [SECURESIGN-655] Enable OIDCs with private or self-signed certificates
  api/v1alpha1/fulcio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  controllers/fulcio/fulcio_controller_test.go
  controllers/fulcio/utils/fulcio_deployment.go
  controllers/fulcio/utils/fulcio_deployment_test.go
Labels: approved, lgtm

#257 SECURESIGN-589 | Fulcio OIDC issuers configuration does not show in Web Form
  api/v1alpha1/fulcio_types.go
  api/v1alpha1/fulcio_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_ctlogs.yaml
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_rekors.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  bundle/manifests/rhtas.redhat.com_trillians.yaml
  bundle/manifests/rhtas.redhat.com_tufs.yaml
  ci/openshift/sign-test.sh
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/samples/rhtas_v1alpha1_fulcio.yaml
  config/samples/rhtas_v1alpha1_securesign.yaml
  controllers/fulcio/actions/servrConfig.go
  controllers/fulcio/fulcio_controller_test.go
  controllers/fulcio/fulcio_hot_update_test.go
  e2e/byodb_test.go
  e2e/common_install_test.go
  e2e/config_update_test.go
  e2e/key_autodiscovery_test.go
  e2e/provided_certs_test.go
Labels: approved, lgtm

#263 Fix Openshift CI's E2E tests
  ci/openshift/sign-test.sh
Labels: approved, lgtm

#265 GA: image updates
  controllers/constants/images.go
Labels: approved, lgtm

#264 run make bundle
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  config/manager/kustomization.yaml
Labels: approved, lgtm

#261 Fix validation error
  controllers/tuf/actions/generate_cert.go
  controllers/tuf/actions/generate_cert_test.go
  go.mod
Labels: approved, lgtm

#267 add-trigger-action
  .github/workflows/trigger-konflux-build.yaml
  .tekton/fbc-v4-13-pull-request.yaml
  .tekton/fbc-v4-13-push.yaml
  .tekton/fbc-v4-14-pull-request.yaml
  .tekton/fbc-v4-14-push.yaml
  .tekton/fbc-v4-15-pull-request.yaml
  .tekton/fbc-v4-15-push.yaml
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved, lgtm

#269 update-images
  controllers/constants/images.go
Labels: approved, lgtm

#271 GA: fbc image updates
  .tekton/fbc-v4-13-pull-request.yaml
  .tekton/fbc-v4-13-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved, lgtm

#272 generating new builds
  fbc/v4.13/catalog.Dockerfile
  fbc/v4.14/catalog.Dockerfile
  fbc/v4.15/catalog.Dockerfile
Labels: approved

#273 run-make-bundle
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: approved

#275 run-make-bundle
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: approved

#276 trigger bundle build
  bundle.Dockerfile
Labels: approved

#278 update fbc images
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#280 [SECURESIGN-681] Move TreeID to status field
  api/v1alpha1/ctlog_types.go
  api/v1alpha1/rekor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_ctlogs.yaml
  bundle/manifests/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_ctlogs.yaml
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  controllers/common/action/base_action.go
  controllers/ctlog/actions/createTree.go
  controllers/ctlog/actions/serverConfig.go
  controllers/rekor/actions/server/createTree.go
  controllers/rekor/utils/rekor_deployment.go
Labels: approved, lgtm

#281 [SECURESIGN-683] Fix autodiscovery of Fulcio Root CA in CTlog
  controllers/common/test/action/support.go
  controllers/ctlog/actions/handle_fulcio_root.go
  controllers/ctlog/actions/handle_fulcio_root_test.go
Labels: approved, lgtm

#260 Implementation of Segment Backup Job and Cronjob
  api/v1alpha1/common.go
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/rbac/role.yaml
  config/samples/rhtas_v1alpha1_securesign.yaml
  controllers/common/utils/kubernetes/job.go
  controllers/common/utils/kubernetes/role.go
  controllers/common/utils/kubernetes/role_binding.go
  controllers/constants/images.go
  controllers/rekor/actions/server/monitoring.go
  controllers/securesign/actions/constants.go
  controllers/securesign/actions/segment_backup_cronjob.go
  controllers/securesign/actions/segment_backup_job.go
  controllers/securesign/securesign_controller.go
  main.go
Labels: approved

#283 run make bundle
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_rekors.yaml
  config/manager/kustomization.yaml
Labels: approved

#284 GA: update fbc images
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#285 revert to 4.14
  fbc/v4.15/catalog.Dockerfile
Labels: approved

#287 trigger rebuild
  fbc/v4.15/ci
Labels: approved

#288 fix-sbj-cluster-role
  controllers/securesign/actions/segment_backup_cronjob.go
  controllers/securesign/actions/segment_backup_job.go
Labels: approved, lgtm

#290 fbc-images
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved

#291 trigger builds
  fbc/v4.13/catalog.Dockerfile
  fbc/v4.14/catalog.Dockerfile
  fbc/v4.15/catalog.Dockerfile
Labels: approved

#292 [SECURESIGN-704] Create ClusterRoleBinding per instance
  config/rbac/role.yaml
  controllers/common/utils/kubernetes/role.go
  controllers/common/utils/kubernetes/role_binding.go
  controllers/constants/images.go
  controllers/constants/labels.go
  controllers/securesign/actions/rbac.go
  controllers/securesign/actions/segment_backup_cronjob.go
  controllers/securesign/actions/segment_backup_job.go
  controllers/securesign/securesign_controller.go
Labels: approved, lgtm

#293 updating the bundle based on SECURESIGN-704
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#295 forgot to bump operator version in csv + makefile
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#294 updating FBCs with new shas @ 03/28/24 1:38 PST
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.13/graph.yaml
  fbc/v4.14/catalog/rhtas-operator/catalog.json
  fbc/v4.14/graph.yaml
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.15/graph.yaml
Labels: approved, do-not-merge/hold
