Repository securesign/secure-sign-operator, pull requests merged in 2024-02, with the labels that each got.

#194 EKS support and testing
  .github/workflows/main.yml
  controllers/trillian/actions/db/deployment.go
  controllers/trillian/utils/trillian-db.go
Labels: approved, lgtm

#197 job for openshift CI
  ci/openshift/job.yaml
Labels: approved, lgtm

#198 regen FBC with opm 1.27.1
  fbc/v4.14/catalog/rhtas-operator/catalog.json
Labels: approved, lgtm

#199 add preflight testing steps
  fbc/fbc-preflight-testing-steps
Labels: approved

#202 updating all fbcs to regen with opm 1.27.1
  fbc/v4.11/catalog/rhtas-operator/catalog.json
  fbc/v4.12/catalog/rhtas-operator/catalog.json
  fbc/v4.13/catalog/rhtas-operator/catalog.json
  fbc/v4.15/catalog/rhtas-operator/catalog.json
  fbc/v4.16/catalog/rhtas-operator/catalog.json
Labels: approved, lgtm

#203 fix of retain functionality
  .github/workflows/main.yml
  api/v1alpha1/common.go
  api/v1alpha1/rekor_types.go
  api/v1alpha1/trillian_types.go
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_trillians.yaml
  controllers/trillian/actions/db/pvc.go
Labels: approved, lgtm

#209 Manually ensuring nothing was missed gamma to main
  Dockerfile
  Makefile
  bundle.Dockerfile
  fbc/fbc-preflight-testing-steps
  fbc/generate-fbc.sh
  tas-env-generate.sh
Labels: approved, lgtm

#213 modify the default value of database
  api/v1alpha1/trillian_types.go
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_trillians.yaml
  e2e/byodb_test.go
  e2e/common_install_test.go
  e2e/config_update_test.go
  e2e/key_autodiscovery_test.go
  e2e/provided_certs_test.go
Labels: approved, lgtm, do-not-merge/work-in-progress

#214 Quick hack for Openshift testing
  ci/openshift/job.yaml
  ci/openshift/sign-test.sh
Labels: approved, lgtm

#215 fix tas keycloak install script
  ci/openshift/tas-keycloak-install.sh
Labels: approved, lgtm

#201 update dockerfiles, update pipelines, add fbc images
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
  Dockerfile.rhtas-operator.rh
  bundle.Dockerfile
  fbc/generate-fbc.sh
Labels: approved, lgtm

#221 fix: Fix EC in Konflux
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#216 Improve error handling
  controllers/ctlog/actions/deployment.go
  controllers/ctlog/utils/ctlog_deployment.go
  controllers/fulcio/actions/deployment.go
  controllers/fulcio/utils/fulcio_deployment.go
  controllers/rekor/actions/server/deployment.go
  controllers/rekor/utils/rekor_deployment.go
  controllers/rekor/utils/search.go
  controllers/trillian/actions/db/deployment.go
  controllers/trillian/actions/logserver/deployment.go
  controllers/trillian/actions/logsigner/deployment.go
  controllers/trillian/utils/trillian-db.go
  controllers/trillian/utils/trillian-deployment.go
Labels: approved, lgtm

#224 Swap ctlog image based on midstream and konflux
  controllers/constants/images.go
Labels: approved, lgtm

#225 include yaml in file and dont curl
  ci/openshift/sign-test.sh
Labels: approved, lgtm

#229 replacing values to represent TAS
  .github/workflows/main.yml
  ci/openshift/sign-test.sh
  e2e/byodb_test.go
  e2e/common_install_test.go
  e2e/config_update_test.go
  e2e/key_autodiscovery_test.go
  e2e/provided_certs_test.go
  e2e/support/oidc.go
Labels: approved, lgtm

#228 Add validation conditions for Trillian resource
  Makefile
  api/v1alpha1/common.go
  api/v1alpha1/suite_test.go
  api/v1alpha1/trillian_types.go
  api/v1alpha1/trillian_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rhtas.redhat.com_ctlogs.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_trillians.yaml
  config/crd/bases/rhtas.redhat.com_tufs.yaml
  config/rbac/role.yaml
  controllers/common/utils/kubernetes/pvc.go
  controllers/common/utils/optional.go
  controllers/ctlog/suite_test.go
  controllers/fulcio/suite_test.go
  controllers/rekor/actions/server/pvc.go
  controllers/rekor/suite_test.go
  controllers/trillian/actions/db/deployment.go
  controllers/trillian/actions/db/handle_secret.go
  controllers/trillian/actions/db/initialize.go
  controllers/trillian/actions/db/pvc.go
  controllers/trillian/actions/db/svc.go
  controllers/trillian/suite_test.go
  controllers/trillian/trillian_controller_test.go
  controllers/tuf/suite_test.go
  e2e/byodb_test.go
  e2e/common_install_test.go
  e2e/config_update_test.go
  e2e/key_autodiscovery_test.go
  e2e/provided_certs_test.go
Labels: approved, lgtm

#231 release candidate images
  controllers/constants/images.go
Labels: approved, lgtm

#232 Add validation conditions for TUF and Rekor resources
  api/v1alpha1/common.go
  api/v1alpha1/rekor_types.go
  api/v1alpha1/rekor_types_test.go
  api/v1alpha1/suite_test.go
  api/v1alpha1/trillian_types_test.go
  api/v1alpha1/tuf_types.go
  api/v1alpha1/tuf_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rhtas.redhat.com_ctlogs.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_tufs.yaml
  controllers/rekor/actions/backfillRedis/backfill_redis_cronjob.go
  controllers/rekor/rekor_controller_test.go
  controllers/rekor/rekor_hot_update_test.go
Labels: approved, lgtm
