Repository securesign/secure-sign-operator, pull requests merged in 2024-08, with the labels that each got.

#533 logging: Replace zap logger by klog
  api/v1alpha1/suite_test.go
  cmd/main.go
  go.mod
  go.sum
  internal/controller/ctlog/ctlog_controller.go
  internal/controller/ctlog/suite_test.go
  internal/controller/fulcio/fulcio_controller.go
  internal/controller/fulcio/suite_test.go
  internal/controller/rekor/rekor_controller.go
  internal/controller/rekor/suite_test.go
  internal/controller/trillian/suite_test.go
  internal/controller/trillian/trillian_controller.go
  internal/controller/tuf/suite_test.go
  internal/controller/tuf/tuf_controller.go
Labels: approved, lgtm

#535 chore: update checkout and setup-go actions
  .github/workflows/main.yml
Labels: approved, lgtm

#539 Migrate images to new repos
  Makefile
  ci/dev-images.sed
  internal/controller/constants/images.go
Labels: approved, lgtm

#542 Update rekor-redis image sha
  internal/controller/constants/images.go
Labels: approved

#543 feat: add prefix parameter into Fulcio's ctlog config
  api/v1alpha1/common.go
  api/v1alpha1/fulcio_types.go
  api/v1alpha1/fulcio_types_test.go
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  internal/controller/fulcio/utils/errors.go
  internal/controller/fulcio/utils/fulcio_deployment.go
  internal/controller/fulcio/utils/fulcio_deployment_test.go
Labels: approved, lgtm

#545 refactor: fix e2e tests to pass golangci linter
  .golangci.yml
  test/e2e/byodb_test.go
  test/e2e/cli_server_test.go
  test/e2e/common_install_test.go
  test/e2e/config_update_test.go
  test/e2e/key_autodiscovery_test.go
  test/e2e/provided_certs_test.go
  test/e2e/support/common.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#551 update-images
  internal/controller/constants/images.go
Labels: approved, lgtm

#554 chore: update rekor image
  internal/controller/constants/images.go
Labels: approved, lgtm

#555 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved, lgtm, ok-to-test

#556 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved, lgtm, ok-to-test

#563 chore: patch-tsa-upgrade-test
  test/e2e/byodb_test.go
  test/e2e/common_install_test.go
  test/e2e/config_update_test.go
  test/e2e/key_autodiscovery_test.go
  test/e2e/provided_certs_test.go
  test/e2e/support/tas/tsa.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#562 refactor: switch from docker to go-containerregistry implementation
  go.mod
  go.sum
  test/e2e/support/common.go
Labels: approved, lgtm

#566 SECURESIGN-1015 | Configure ingress sharding
  api/v1alpha1/common.go
  api/v1alpha1/rekor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_rekors.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  bundle/manifests/rhtas.redhat.com_timestampauthorities.yaml
  bundle/manifests/rhtas.redhat.com_tufs.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_timestampauthorities.yaml
  config/crd/bases/rhtas.redhat.com_tufs.yaml
  internal/controller/common/utils/kubernetes/ingress.go
  internal/controller/rekor/actions/ui/ingress.go
Labels: approved, lgtm

#564 fix: check observed, available and new replica set statuses to decide if deployment is ready
  internal/controller/common/utils/kubernetes/deployment.go
  internal/controller/ctlog/actions/initialize.go
  internal/controller/ctlog/ctlog_controller_test.go
  internal/controller/ctlog/ctlog_hot_update_test.go
  internal/controller/fulcio/actions/initialize.go
  internal/controller/fulcio/fulcio_controller_test.go
  internal/controller/fulcio/fulcio_hot_update_test.go
  internal/controller/rekor/actions/redis/initialize.go
  internal/controller/rekor/actions/server/generate_signer.go
  internal/controller/rekor/actions/server/initialize.go
  internal/controller/rekor/actions/server/resolve_pub_key.go
  internal/controller/rekor/actions/ui/initialize.go
  internal/controller/rekor/rekor_controller_test.go
  internal/controller/rekor/rekor_hot_update_test.go
  internal/controller/trillian/actions/db/initialize.go
  internal/controller/trillian/actions/logserver/initialize.go
  internal/controller/trillian/actions/logsigner/initialize.go
  internal/controller/trillian/trillian_controller_test.go
  internal/controller/tsa/actions/initialize.go
  internal/controller/tsa/timestampauthority_controller_test.go
  internal/controller/tsa/tsa_hot_update_test.go
  internal/controller/tuf/actions/initialize.go
  internal/controller/tuf/tuf_controller_test.go
  internal/controller/tuf/tuf_hot_update_test.go
  internal/testing/kubernetes/deployment.go
Labels: approved, lgtm

#561 [SECURESIGN-574] Independently Deployable CT-log
  internal/controller/ctlog/actions/pending.go
  internal/controller/ctlog/ctlog_controller.go
  internal/controller/ctlog/ctlog_controller_test.go
Labels: approved, lgtm, ok-to-test

#557 SECURESIGN-842 | Operator's metrics are not consumed by OCP monitor
  .github/workflows/main.yml
  bundle/manifests/rhtas-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/rhtas-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/rhtas-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/default/manager_metrics_patch.yaml
  config/manager/kustomization.yaml
  config/manager/metrics_service.yaml
  config/prometheus/monitor.yaml
Labels: approved, lgtm

#565 SECURESIGN-1203 | Add TSA key rotation doc
  docs/tsa-key-rotation.md
Labels: approved, lgtm

#571 doc: CT log signer key rotation and sharding
  docs/ctlog-key-rotation.md
Labels: approved, lgtm

#574 update-images
  internal/controller/constants/images.go
Labels: approved

#570 SECURESIGN-1221 | SBJ Not reaching segment endpoint
  internal/controller/securesign/actions/segment_backup_cronjob.go
  internal/controller/securesign/actions/segment_backup_job.go
Labels: approved, lgtm

#582 fix(rekor): create new secret only for generated signer key
  internal/controller/common/utils/kubernetes/deployment.go
  internal/controller/rekor/actions/server/generate_signer.go
  internal/controller/rekor/actions/server/generate_signer_test.go
  test/e2e/config_update_test.go
Labels: approved, lgtm

#583 fix: check if lates progressing status is for current deployment temp…
  .github/workflows/main.yml
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/common/utils/kubernetes/deployment.go
  internal/controller/securesign/securesign_controller.go
Labels: approved, lgtm

#548 refactor: split config update based on component
  .github/workflows/main.yml
  .gitignore
  Makefile
  internal/controller/tsa/actions/generate_signer_test.go
  internal/controller/tsa/tsa_hot_update_test.go
  test/.DS_Store
  test/e2e/.DS_Store
  test/e2e/byodb_test.go
  test/e2e/common_install_test.go
  test/e2e/config_update_test.go
  test/e2e/custom_install/proxy.go
  test/e2e/key_autodiscovery_test.go
  test/e2e/provided_certs_test.go
  test/e2e/support/cert.go
  test/e2e/support/common.go
  test/e2e/support/tas/ctlog.go
  test/e2e/support/tas/ctlog/ctlog.go
  test/e2e/support/tas/fulcio/fulcio.go
  test/e2e/support/tas/rekor.go
  test/e2e/support/tas/rekor/rekor.go
  test/e2e/support/tas/rekor/search_ui.go
  test/e2e/support/tas/securesign/securesign.go
  test/e2e/support/tas/tas.go
  test/e2e/support/tas/trillian.go
  test/e2e/support/tas/trillian/trillian.go
  test/e2e/support/tas/tsa.go
  test/e2e/support/tas/tsa/tsa.go
  test/e2e/support/tas/tuf/tuf.go
  test/e2e/update/ctlog_test.go
  test/e2e/update/fulcio_test.go
  test/e2e/update/rekor_test.go
  test/e2e/update/suite_test.go
  test/e2e/update/tsa_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm
