Repository securesign/secure-sign-operator, pull requests merged in 2024-10, with the labels that each got.

#660 test: extend client server scenario by updatetree createtree and tuftool
  test/e2e/cli_server_test.go
Labels: approved, lgtm

#662 update rekor and cli images
  internal/controller/constants/images.go
Labels: approved, lgtm

#661 Resolve SECURESIGN-1405
  docs/fulcio-key-rotation.md
  internal/controller/common/action/base_action.go
  internal/controller/fulcio/actions/generateCert_test.go
  internal/controller/fulcio/actions/generate_cert.go
  internal/controller/fulcio/utils/fulcio_secrets.go
Labels: approved, lgtm

#664 RC5: update images
  internal/controller/constants/images.go
Labels: lgtm

#666 RC5: make bundle
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#669 [SECURESIGN-1455] Fix Ensure function
  internal/controller/common/action/base_action.go
Labels: approved, lgtm

#672 [SECURESIGN-1458] Update TUF component files
  internal/controller/tuf/actions/pvc.go
  internal/controller/tuf/actions/resolve_keys.go
  internal/controller/tuf/actions/resolve_keys_test.go
Labels: approved, lgtm

#673 refactor: constants for app.kubernetes.io labels
  internal/clidownload/component.go
  internal/controller/common/utils/kubernetes/common.go
  internal/controller/constants/labels.go
  internal/controller/ctlog/ctlog_controller.go
  internal/controller/securesign/actions/segment_rbac.go
  internal/controller/securesign/securesign_controller.go
  test/e2e/byodb_test.go
  test/e2e/support/tas/ctlog/ctlog.go
  test/e2e/support/tas/fulcio/fulcio.go
  test/e2e/support/tas/rekor/rekor.go
  test/e2e/support/tas/rekor/search_ui.go
  test/e2e/support/tas/trillian/trillian.go
  test/e2e/support/tas/tsa/tsa.go
  test/e2e/support/tas/tuf/tuf.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#671 [SECURESIGN-1455] Fix rekor-server component
  internal/controller/common/utils/kubernetes/config_map.go
  internal/controller/common/utils/kubernetes/secret.go
  internal/controller/rekor/actions/server/generate_signer.go
  internal/controller/rekor/actions/server/generate_signer_test.go
  internal/controller/rekor/actions/server/pvc.go
  internal/controller/rekor/actions/server/resolve_pub_key.go
  internal/controller/rekor/actions/server/resolve_pub_key_test.go
  internal/controller/rekor/actions/server/sharding_config.go
  internal/controller/rekor/actions/server/sharding_config_test.go
Labels: approved, lgtm

#674 SECURESIGN-1461: check if Trillian's secret with db connection already exists
  internal/controller/trillian/actions/db/handle_secret.go
  internal/controller/trillian/actions/db/handle_secret_test.go
  internal/controller/trillian/actions/db/pvc.go
  internal/controller/trillian/trillian_controller.go
  internal/controller/trillian/utils/constants.go
  internal/controller/trillian/utils/server-deployment.go
  internal/controller/trillian/utils/signer-deployment.go
  internal/controller/trillian/utils/trillian-db.go
Labels: approved, lgtm, jira/valid-reference

#677 Ensure that Fulcio component does not create duplicated resources
  internal/controller/fulcio/actions/generateCert_test.go
  internal/controller/fulcio/actions/servrConfig.go
  internal/controller/fulcio/actions/servrConfig_test.go
Labels: approved, lgtm

#686 Ensure that CTLog component does not create duplicated resources
  internal/controller/ctlog/actions/constants.go
  internal/controller/ctlog/actions/handle_fulcio_root.go
  internal/controller/ctlog/actions/handle_fulcio_root_test.go
  internal/controller/ctlog/actions/handle_keys.go
  internal/controller/ctlog/actions/handle_keys_test.go
  internal/controller/ctlog/actions/server_config.go
  internal/controller/ctlog/actions/server_config_test.go
  internal/controller/ctlog/ctlog_hot_update_test.go
  internal/controller/ctlog/utils/ctlog_config.go
  internal/controller/ctlog/utils/keys.go
Labels: approved, lgtm

#693 fix(ctlog): cleanup only linked server configs
  internal/controller/ctlog/actions/constants.go
  internal/controller/ctlog/actions/handle_fulcio_root.go
  internal/controller/ctlog/actions/handle_fulcio_root_test.go
  internal/controller/ctlog/actions/handle_keys.go
  internal/controller/ctlog/actions/resolve_tree.go
  internal/controller/ctlog/actions/server_config.go
  internal/controller/ctlog/actions/server_config_test.go
  internal/controller/ctlog/ctlog_controller.go
Labels: approved, lgtm

#694 fix(fulcio): delete all unassigned server config maps
  internal/controller/fulcio/actions/generate_cert.go
  internal/controller/fulcio/actions/generate_cert_test.go
  internal/controller/fulcio/actions/server_config.go
  internal/controller/fulcio/actions/server_config_test.go
Labels: approved, lgtm

#679 fix: Resolving rekor pub key locally against openshift
  internal/controller/rekor/actions/server/resolve_pub_key.go
  internal/controller/rekor/rekor_controller_test.go
Labels: approved, lgtm

#675 SECURESIGN-1460 | Ensure that TSA component does not create duplicated resources
  api/v1alpha1/timestampauthority_types.go
  api/v1alpha1/timestampauthority_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  bundle/manifests/rhtas.redhat.com_timestampauthorities.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_timestampauthorities.yaml
  internal/controller/common/action/base_action.go
  internal/controller/securesign/actions/ensure_tsa.go
  internal/controller/tsa/actions/deployment.go
  internal/controller/tsa/actions/generate_signer.go
  internal/controller/tsa/actions/generate_signer_test.go
  internal/controller/tsa/actions/ingress.go
  internal/controller/tsa/actions/initialize.go
  internal/controller/tsa/actions/monitoring.go
  internal/controller/tsa/actions/ntpMonitoring.go
  internal/controller/tsa/actions/ntpMonitoring_test.go
  internal/controller/tsa/actions/rbac.go
  internal/controller/tsa/actions/service.go
  internal/controller/tsa/timestampauthority_controller_test.go
  internal/controller/tsa/tsa_hot_update_test.go
  internal/controller/tsa/utils/tsa_cert_chain.go
  internal/testing/common/tsa/tsa.go
  test/e2e/byodb_test.go
  test/e2e/common_install_test.go
  test/e2e/custom_install/proxy.go
  test/e2e/update/suite_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#699 RC6: run bundle
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#702 add_rpm_scan
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved, lgtm

#703 add_rpm_scan_release-1.0
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
Labels: approved

#670 test: benchmark e2e install scenario
  test/e2e/benchmark/install_test.go
  test/e2e/support/condition/condition.go
  test/e2e/support/oidc.go
  test/e2e/support/tas/ctlog/ctlog.go
  test/e2e/support/tas/fulcio/fulcio.go
  test/e2e/support/tas/rekor/rekor.go
  test/e2e/support/tas/rekor/search_ui.go
  test/e2e/support/tas/securesign/securesign.go
  test/e2e/support/tas/trillian/trillian.go
  test/e2e/support/tas/tsa/tsa.go
  test/e2e/support/tas/tuf/tuf.go
Labels: approved, lgtm
