Repository securesign/secure-sign-operator, pull requests merged in 2025-04, with the labels that each got.

#1001 chore: httpd server and ose tools images
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm, dependencies

#1003 Update build pipelines
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
Labels: approved

#960 :robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1005 Manually triggering build
  Dockerfile.rhtas-operator.rh
Labels: approved

#1004 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1007 chore: configure renovate bot
  renovate.json
Labels: approved, lgtm

#1010 [release-1.1] Bump to v1.1.2
  .github/workflows/main.yml
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  Makefile
  bundle.Dockerfile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved

#1011 chore: generate CSV containerImage annotation
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
Labels: approved, lgtm

#1021 Update Component Images for 1.1.2
  internal/controller/constants/images.go
Labels: approved, lgtm

#1022 Generate bundle for v1.1.2
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved

#1025 :robot: [RHTAS-build-bot] [release-1.1] Update Component images
  internal/controller/constants/images.go
Labels: approved, lgtm

#1024 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#1026 :robot: [RHTAS-build-bot] [release-1.1] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved

#1028 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1027 :robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
Labels: approved, lgtm

#1029 :robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: approved, lgtm

#1034 chore: add latest 1.1.2 release into fbc
  .github/workflows/main.yml
Labels: approved

#1033 fix: add Fulcio's legacy unix socket into no_proxy env vars
  internal/controller/common/utils/kubernetes/ensure/deployment/deployment.go
  internal/controller/common/utils/kubernetes/ensure/set_proxy.go
  internal/controller/common/utils/kubernetes/ensure/set_proxy_test.go
  internal/controller/fulcio/actions/deployment.go
Labels: approved, lgtm

#1047 fix: add fulcio's legacy unix socket into no_proxy env vars
  internal/controller/common/utils/set_proxy.go
  internal/controller/common/utils/set_proxy_test.go
  internal/controller/fulcio/utils/fulcio_deployment.go
Labels: approved, lgtm

#1048 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved

#1049 :robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
Labels: approved

#1050 :robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: approved, lgtm

#1051 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm, ok-to-test

#1054 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1052 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm, ok-to-test

#1053 :robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manager/kustomization.yaml
Labels: approved, lgtm

#1058 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#1060 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1061 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#1062 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1059 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#1076 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#1074 refactor: remove prometheus-operator dependency
  cmd/main.go
  go.mod
  go.sum
  internal/controller/common/utils/kubernetes/ensure/ensure_test.go
  internal/controller/common/utils/kubernetes/service_moniter.go
  internal/controller/common/utils/kubernetes/service_moniter_test.go
  internal/controller/ctlog/actions/monitoring.go
  internal/controller/fulcio/actions/monitoring.go
  internal/controller/rekor/actions/server/monitoring.go
  internal/controller/trillian/actions/logserver/monitoring.go
  internal/controller/trillian/actions/logsigner/monitoring.go
  internal/controller/tsa/actions/monitoring.go
  internal/testing/action/support.go
  test/e2e/support/common.go
Labels: approved, lgtm
