Repository securesign/secure-sign-operator, pull requests merged in 2025-03, with the labels that each got.

#892 ci: fix FBC replaces version of operator
  .github/workflows/main.yml
Labels: approved, lgtm

#901 Update Channel Labels for 1.2.0
  bundle.Dockerfile
Labels: approved, lgtm

#849 Migrate Failures to Error function
  internal/controller/common/action/base_action.go
  internal/controller/ctlog/actions/handle_fulcio_root.go
  internal/controller/ctlog/actions/initialize.go
  internal/controller/ctlog/actions/server_config.go
  internal/controller/fulcio/actions/generate_cert.go
  internal/controller/fulcio/actions/initialize.go
  internal/controller/fulcio/actions/status_url.go
  internal/controller/rekor/actions/redis/initialize.go
  internal/controller/rekor/actions/server/initialize.go
  internal/controller/rekor/actions/server/resolve_pub_key.go
  internal/controller/rekor/actions/server/resolve_pub_key_test.go
  internal/controller/rekor/actions/server/status_url.go
  internal/controller/rekor/actions/ui/initialize.go
  internal/controller/rekor/actions/ui/status_url.go
  internal/controller/trillian/actions/db/handle_secret.go
  internal/controller/trillian/actions/db/handle_secret_test.go
  internal/controller/trillian/actions/db/initialize.go
  internal/controller/trillian/actions/logserver/initialize.go
  internal/controller/trillian/actions/logsigner/initialize.go
  internal/controller/tsa/actions/initialize.go
  internal/controller/tsa/actions/ntpMonitoring.go
  internal/controller/tsa/actions/ntpMonitoring_test.go
  internal/controller/tsa/actions/status_url.go
  internal/controller/tuf/actions/initialize.go
  internal/controller/tuf/actions/status-url.go
  internal/testing/action/result.go
Labels: approved, lgtm

#903 Fix Replace images in ci
  .github/workflows/main.yml
Labels: approved, lgtm

#914 Release-1.2: update konflux refrences, update bundle refrences
  .github/workflows/main.yml
  .tekton/project_resources/devstream.yaml
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  .tekton/rhtas-operator-pull-request.yaml
  .tekton/rhtas-operator-push.yaml
  Makefile
  bundle.Dockerfile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved

#918 Related images 1.2
  .github/workflows/main.yml
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  ci/related-image-patch.sh
  cmd/main.go
  config/default/images.env
  config/default/kustomization.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_images_patch.yaml
  config/env/kubernetes/kustomization.yaml
  config/env/openshift/kustomization.yaml
  config/env/openshift/manager_openshift_patch.yaml
  config/manifests/kustomization.yaml
  internal/clidownload/component.go
  internal/controller/common/utils/flag_or_env.go
  internal/controller/constants/images.go
  internal/controller/ctlog/utils/ctlog_deployment.go
  internal/controller/fulcio/utils/fulcio_deployment.go
  internal/controller/rekor/actions/backfillRedis/backfill_redis_cronjob.go
  internal/controller/rekor/utils/redis_deployment.go
  internal/controller/rekor/utils/rekor_deployment.go
  internal/controller/rekor/utils/rekor_search_ui_deployment.go
  internal/controller/securesign/actions/segment_backup_cronjob.go
  internal/controller/securesign/actions/segment_backup_job.go
  internal/controller/trillian/actions/logserver/deployment.go
  internal/controller/trillian/actions/logsigner/deployment.go
  internal/controller/trillian/utils/server-deployment.go
  internal/controller/trillian/utils/signer-deployment.go
  internal/controller/trillian/utils/trillian-db.go
  internal/controller/tsa/utils/tsa_deployment.go
  internal/controller/tuf/utils/tuf_deployment.go
  internal/controller/tuf/utils/tuf_init_job.go
  internal/images/images.env
  internal/images/images.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#878 feat(retrievePodLogs): fetch logs from pods and add to zip
  test/e2e/support/common.go
Labels: approved, lgtm, ok-to-test

#902 :robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#929 test: use grc mirror to pull httpd image
  test/e2e/custom_install/proxy.go
Labels: approved, lgtm

#926 fix: Add missing flag for RELATED_IMAGE_TRILLIAN_CREATE_TREE
  cmd/main.go
Labels: approved, lgtm

#931 test: remove unmaintained actions-rs/toolchain step from github workflow
  .github/workflows/main.yml
Labels: approved

#919 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#927 :robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, ok-to-test

#932 fix: mount kubernetes api server certificate to /var/run/fulcio/ca.crt
  internal/controller/fulcio/actions/deployment.go
Labels: approved, lgtm

#921 [SECURESIGN-1891] Fix configuration of attestation storage so Rekor c…
  internal/controller/rekor/utils/rekor_deployment.go
Labels: approved, lgtm

#936 fix: build bundle image from scratch
  bundle.Dockerfile
Labels: approved, lgtm

#933 [release-1.2] fix: mount kubernetes api server certificate to /var/run/fulcio/ca.crt
  internal/controller/fulcio/utils/fulcio_deployment.go
Labels: approved, lgtm

#913 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#937 [release-1.2] fix: build bundle image from scratch
  .tekton/rhtas-operator-bundle-pull-request.yaml
  .tekton/rhtas-operator-bundle-push.yaml
  bundle.Dockerfile
Labels: approved, lgtm

#940 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved

#941 fix: mandatory labels for bundle image
  bundle.Dockerfile
Labels: approved, lgtm

#930 fix: panic error when TSA configuration is nil in Securesign resource
  internal/controller/securesign/actions/ensure_tsa.go
  internal/controller/securesign/actions/update_status.go
Labels: approved, lgtm

#942 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#944 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#945 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#938 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#948 chore: update go module version and controller tools
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas.redhat.com_ctlogs.yaml
  bundle/manifests/rhtas.redhat.com_fulcios.yaml
  bundle/manifests/rhtas.redhat.com_rekors.yaml
  bundle/manifests/rhtas.redhat.com_securesigns.yaml
  bundle/manifests/rhtas.redhat.com_timestampauthorities.yaml
  bundle/manifests/rhtas.redhat.com_trillians.yaml
  bundle/manifests/rhtas.redhat.com_tufs.yaml
  cmd/main.go
  config/crd/bases/rhtas.redhat.com_ctlogs.yaml
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_timestampauthorities.yaml
  config/crd/bases/rhtas.redhat.com_trillians.yaml
  config/crd/bases/rhtas.redhat.com_tufs.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/ctlog/ctlog_controller.go
  internal/controller/fulcio/fulcio_controller.go
  internal/controller/rekor/rekor_controller.go
  internal/controller/securesign/securesign_controller.go
  internal/controller/trillian/trillian_controller.go
  internal/controller/tsa/timestampauthority_controller.go
  internal/controller/tuf/tuf_controller.go
  internal/metrics/metrics.go
Labels: approved, lgtm

#946 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#949 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#951 [release-1.2] fix: Instability of cleanup process of old configmaps and secrets
  internal/controller/ctlog/actions/server_config.go
  internal/controller/fulcio/actions/server_config.go
  internal/controller/rekor/actions/server/sharding_config.go
  test/e2e/support/common.go
Labels: approved, lgtm

#947 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#954 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#958 fix: container images to include OS licensing at /licenses
  Dockerfile.rhtas-operator.rh
  bundle.Dockerfile
Labels: approved, lgtm

#966 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved

#965 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved

#971 Update channel lables 1.2
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#969 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#972 :robot: [RHTAS-build-bot] [release-1.2] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#950 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#970 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
  internal/images/images.env
Labels: approved, lgtm

#973 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  bundle/manifests/rhtas-related-images_v1_configmap.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#974 :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image
  Makefile
  bundle/manifests/rhtas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#977 ci: add configuration for generated release notes
  .github/release.yaml
Labels: approved, lgtm

#997 fix: excluded bot account in .github/release.yaml
  .github/release.yaml
Labels: approved, lgtm

#996 chore: configure renovate bot to constraint to go1.23
  renovate.json
Labels: approved, lgtm
