Repository securesign/secure-sign-operator, pull requests merged in 2025-06, with the labels that each got.

#851 feat: use kubernetes lease election for Trillian log signer
  config/default/images.env
  config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/trillian/actions/logsigner/deployment.go
  internal/controller/trillian/actions/logsigner/rbac.go
  internal/controller/trillian/trillian_controller.go
  internal/controller/trillian/utils/server-deployment.go
Labels: enhancement, approved

#1153 feat: extend Fulcio by affinity, tolerations, resources and replicas
  api/v1alpha1/fulcio_types.go
  api/v1alpha1/fulcio_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rhtas.redhat.com_fulcios.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/manifests/kustomization.yaml
  config/manifests/patches/fulcio_descriptors.yaml
  config/manifests/patches/trillian_descriptors.yaml
  internal/controller/fulcio/actions/deployment.go
Labels: enhancement

#1158 :robot: [RHTAS-build-bot] [main] Update Component images
  config/default/images.env
Labels: dependencies

#1162 feat: extend TSA by affinity, tolerations, resources and replicas
  api/v1alpha1/timestampauthority_types.go
  api/v1alpha1/timestampauthority_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  config/crd/bases/rhtas.redhat.com_timestampauthorities.yaml
  config/manifests/kustomization.yaml
  config/manifests/patches/timestampauthority_descriptions.yaml
  internal/controller/tsa/actions/deployment.go
Labels: enhancement

#1159 feat: Rekor search-index tls
  api/v1alpha1/rekor_types.go
  api/v1alpha1/rekor_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rhtas.redhat.com_rekors.yaml
  config/crd/bases/rhtas.redhat.com_securesigns.yaml
  internal/controller/rekor/actions/backfillRedis/backfill_redis_cronjob.go
  internal/controller/rekor/actions/backfillRedis/helper.go
  internal/controller/rekor/actions/backfillRedis/helper_test.go
  internal/controller/rekor/actions/constants.go
  internal/controller/rekor/actions/searchIndex/redis/actions/deployment.go
  internal/controller/rekor/actions/searchIndex/redis/actions/generate_password.go
  internal/controller/rekor/actions/searchIndex/redis/actions/helper.go
  internal/controller/rekor/actions/searchIndex/redis/actions/svc.go
  internal/controller/rekor/actions/searchIndex/redis/actions/tls.go
  internal/controller/rekor/actions/searchIndex/redis/options.go
  internal/controller/rekor/actions/searchIndex/util.go
  internal/controller/rekor/actions/server/deployment.go
  internal/controller/rekor/rekor_controller.go
  internal/utils/kubernetes/ensure/auth.go
  test/e2e/byodb_test.go
Labels: enhancement
